train:
  # general
  batch_size: 128
  max_nb_epochs: 100
  learning_rate: 0.001
  noise: gaussian
  noise_ratio: 0.01
  use_early_stop: false
  tags:
    - "noise-gaussian"
  # device
  gpus: null
  distributed_backend: null
  # precision
  precision: 32
  amp_level: O0
  # etc
  profile: false
  fast_dev_run: false
  val_percent_check: 1.0
