train:
  # general
  batch_size: 64
  max_nb_epochs: 500
  learning_rate: 0.00001
  # device
  gpus: ""
  distributed_backend: null
  # precision
  precision: 32
  amp_level: O0
  # etc
  profile: false
  fast_dev_run: false
