train:
  # general
  batch_size: 128
  max_epochs: 200
  learning_rate: 0.00001
  # device
  gpus: null
  distributed_backend: null
  # precision
  precision: 32
  amp_level: O0
  # etc
  profile: false
  fast_dev_run: false
  val_percent_check: 1.0
  train_percent_check: 1.0
  # early stop & logging
  use_early_stop: true
  upload_checkpoints: false
  save_last_checkpoint: false
