train:
  # general
  batch_size: 64
  max_nb_epochs: 100
  learning_rate: 0.001
  use_early_stop: false
  # device
  gpus: null
  distributed_backend: null
  # precision
  precision: 32
  amp_level: O0
  # etc
  profile: false
  fast_dev_run: false
  val_percent_check: 1.0
  train_percent_check: 0.2
  # logging
  upload_checkpoints: false
