train:
  # general
  batch_size: 2048
  max_nb_epochs: 50
  learning_rate: 0.001
  # device
  gpus: null
  distributed_backend: null
  # precision
  precision: 32
  amp_level: O0
  # etc
  profile: false
  fast_dev_run: false
  val_percent_check: 1.0
  train_percent_check: 1.0
  # early stop & logging
  use_early_stop: false
  upload_checkpoints: false
