train:
  # general
  batch_size: 1024
  max_epochs: 500
  learning_rate: 0.00003
  # device
  gpus: null
  distributed_backend: null
  # precision
  precision: 32
  amp_level: O0
  # etc
  profile: false
  fast_dev_run: false
  # early stop & logging
  use_early_stop: true
  early_stop_patience: 20
  upload_checkpoints: false
  save_last_checkpoint: false
