project: "kjang0517/msmarco-2"
experiment:
  name: msmarco-passages
defaults:
  - model: wta
  - dataset: msmarco-passages-fse
  - noise: gaussian
  - model_n: defaults
  - model_k: defaults
  - train: defaults
  - loss: defaults
