project: "kjang0517/news20"
experiment:
  name: news20-tfidf
defaults:
  - model: wta
  - dataset: news20-tfidf
  - noise: gaussian
  - model_n: defaults
  - model_k: defaults
  - train: defaults
  - loss: defaults
