project: "kjang0517/news20"
experiment:
  name: tfidf
  tags:
    - 1-layer
defaults:
  - model: wta
  - dataset: news20-tfidf
  - model_n: defaults
  - model_k: defaults
  - train: defaults
  - loss: defaults
