project: "kjang0517/hotpotqa"
experiment:
  name: hotpotqa-question
defaults:
  - model: wta
  - dataset: hotpotqa-q
  - model_n: defaults
  - model_k: defaults
  - train: defaults
  - loss: defaults
